// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for ios - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCBgczMsZYrnbM2IdOrfQOeQ3qKFo34px8',
//     appId: '1:408344046428:web:4eba6dd42b6a9339ef6f99',
//     messagingSenderId: '408344046428',
//     projectId: 't-store-b6075',
//     authDomain: 't-store-b6075.firebaseapp.com',
//     storageBucket: 't-store-b6075.appspot.com',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyC8-H64ITOUCFI9_3iA0Z7ua7arKJko4rg',
//     appId: '1:408344046428:android:0f240b9021252fadef6f99',
//     messagingSenderId: '408344046428',
//     projectId: 't-store-b6075',
//     storageBucket: 't-store-b6075.appspot.com',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyCCRzeWa6btQ7MFney05kgYwJhC8VPngqU',
//     appId: '1:408344046428:web:90ecec2c0b07a6a0ef6f99',
//     messagingSenderId: '408344046428',
//     projectId: 't-store-b6075',
//     authDomain: 't-store-b6075.firebaseapp.com',
//     storageBucket: 't-store-b6075.appspot.com',
//   );
// }
